name = "tthub"
main = "SRC/index.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "halloweentok-main-db"
database_id = "aca5dca1-2ccd-4874-a8a9-b2e8ca62053a"

# Service binding на первый шард-воркер (склад блобов).
# Добавляй новые [[services]] блоки при деплое shard-worker-2, shard-worker-3 и т.д.
[[services]]
binding = "SHARD_1"
service = "halloweentok-shard-1"

[vars]
GITHUB_CLIENT_ID = "Ov23liOcBF1ktMDKmrrN"
GITHUB_CLIENT_SECRET = "8b6c145b55c0da78c911594527c1dda20442ff64"
INTERNAL_SECRET = "NETPAROLA338"
